sensor:
  - platform: template
    sensors:
      muriatic_tank:
        friendly_name: "Muriatic tank"
        value_template: "{{ states('input_number.muriatic_tank')|round(2)}}"

  - platform: history_stats
    name: muriatic_on_last_hour
    entity_id: switch.ph
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: muriatic_on_last_48h
    entity_id: switch.ph
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00


input_number:
  muriatic_tank:
    min: 0
    max: 30
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
  muriatic_concentration:
    min: 5
    max: 30
    step: .1
    unit_of_measurement: '%'
    icon: mdi:water-percent
    mode: box
  muriatic_speed:
    min: 10
    max: 100
    step: 1
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
  notify_muriatic_high:
    min: 0
    max: 5
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_muriatic_tank:
    min: 0
    max: 5
    step: 0.5
    unit_of_measurement: 'l'
    icon: mdi:flask-empty
  muriatic_inject:
    min: 0
    max: 2000
    step: 5
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box

automation:
- alias: muriatic_every_hour
  id: '1554167717425'
  initial_state: true
  trigger:
  - platform: time_pattern
    minutes: 1
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_tank
      value: " {{ ( states('input_number.muriatic_tank')|float - ( states('sensor.muriatic_on_last_hour')|float * states('input_number.muriatic_speed')|int * 6 / 100 ) ) | round(2) }} "

- alias: muriatic_tank_low
  id: '1559049845419'
  initial_state: true
  trigger:
    platform: template
    value_template: "{% if states('input_number.notify_muriatic_tank')|int> 0 and states('sensor.muriatic_tank')|float < states('input_number.notify_muriatic_tank')|float %}true{% endif %}"
  condition: []
  action:
  - data_template:
      message: "@{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Muriatic tank low ({{states('input_number.muriatic_tank')|float}} liters )!!!"
    service: notify.pushbullet

- alias: muriatic_high
  id: '1559049844489'
  initial_state: true
  trigger:
    platform: template
    value_template: "{% if states('input_number.notify_muriatic_high')|int> 0 and states('sensor.muriatic_on_last_48h')|float > (states('input_number.notify_muriatic_high')|float*100 ) / (states('input_number.muriatic_speed')|float *6) %}true{% endif %}"
  condition: []
  action:
  - entity_id: switch.ph
    service: switch.turn_off
  - entity_id: input_boolean.lock_muriatic
    service: input_boolean.turn_on
  - data_template:
      message: "{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Muriatic inject blocked ({{states('input_number.notify_muriatic_high')}} in 48 hours)!!!"
    service: notify.pushbullet

- alias: muriatic_set
  id: '1559049844459'
  initial_state: true
  trigger: []
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.muriatic_inject
      value: " {{ ( states('input_number.capacity')|float * ( 10 ** (8 - states('input_number.ph_target')|float ) - 10 ** (8 - states('sensor.ph_mean')|float ) ) * (126.19 / states('input_number.muriatic_concentration')|float ) )|round(0)|int }} "
  - service: automation.trigger
    entity_id: automation.muriatic_inject

- alias: muriatic_inject
  id: '1559949826459'
  initial_state: true
  trigger: []
  condition: []
  action:
  - condition: state
    entity_id: input_boolean.lock_muriatic
    state: 'off'
  - condition: numeric_state
    entity_id: input_number.muriatic_inject
    above: 10
  - entity_id: switch.ph
    service: switch.turn_on
  - data_template:
      message: "{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Muriatic injection: ({{states('input_number.muriatic_inject')}} ml)!!!"
    service: notify.pushbullet
  - delay: 00:00:{{ [0 , 60 * states('input_number.muriatic_inject')|float/ states('input_number.muriatic_speed')|float ]|max|int }}
  - entity_id: switch.ph
    service: switch.turn_off
  - data_template:
      message: "{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Muriatic injection end!!!"
    service: notify.pushbullet

