homeassistant:
  name: RaspiPool
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  #customize: !include customize.yaml
  packages: !include_dir_named packages
default_config:
# Disable Discover some devices automatically
# discovery:
tts:
  - platform: google_translate
logger:
  default: critical
  logs:
    homeassistant.components.sensor.atlas_scientific: debug
    homeassistant.components.switch.command_line: debug

group: !include groups.yaml
# Disable automation
# automation: !include automations.yaml
script: !include scripts.yaml
lovelace:
  mode: yaml
