sensor:
  - platform: template
    sensors:
      bleach_tank:
        friendly_name: "Bleach tank"
        value_template: "{{ states('input_number.bleach_tank')|round(2)}}"

  - platform: history_stats
    name: bleach_on_last_hour
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: bleach_on_last_48h
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00

input_number:
  bleach_tank:
    min: 0
    max: 50
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
  bleach_concentration:
    min: 1
    max: 15
    step: .25
    unit_of_measurement: '%'
    icon: mdi:water-percent
    mode: box
  bleach_speed:
    min: 10
    max: 100
    step: 1
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
  notify_bleach_high:
    min: 0
    max: 15
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_bleach_tank:
     min: 0
     max: 5
     step: 0.5
     unit_of_measurement: 'l'
     icon: mdi:flask-empty-outline
  bleach_inject:
    min: 0
    max: 20000
    step: 5
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box


automation:
- alias: bleach_every_hour
  id: '1554367517425'
  initial_state: true
  trigger:
  - platform: time_pattern
    minutes: 1
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_tank
      value: " {{ ( states('input_number.bleach_tank')|float - ( states('sensor.bleach_on_last_hour')|float * states('input_number.bleach_speed')|int * 6 / 100 ) ) | round(2) }} "

- alias: bleach_tank_low
  id: '1559049845420'
  initial_state: true
  trigger:
    platform: template
    value_template: "{% if states('input_number.notify_bleach_tank')|int> 0 and states('sensor.bleach_tank')|float < states('input_number.notify_bleach_tank')|float %}true{% endif %}"
  condition: []
  action:
  - data_template:
      message: "@{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Bleach tank low ({{states('input_number.bleach_tank')|float}} liters )!!!"
    service: notify.pushbullet

- alias: bleach_high
  id: '1559049844490'
  initial_state: true
  trigger:
    platform: template
    value_template: "{% if states('input_number.notify_bleach_high')|int> 0 and states('sensor.bleach_on_last_48h')|float > (states('input_number.notify_bleach_high')|float *100 ) / (states('input_number.bleach_speed')|float *6) %}true{% endif %}"
  condition: []
  action:
  - entity_id: switch.orp
    service: switch.turn_off
  - entity_id: input_boolean.lock_bleach
    service: input_boolean.turn_on
  - data_template:
      message: "{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Bleach inject blocked ({{states('input_number.notify_bleach_high')}} in 48 hours)!!!"
    service: notify.pushbullet

- alias: bleach_set
  id: '1559149839459'
  initial_state: true
  trigger: []
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.bleach_inject
      value: " {{ ( states('input_number.capacity')|float * ( states('input_number.fc_target')|float - states('sensor.e_fc')|float ) * (100 / states('input_number.bleach_concentration')|float ), 0)|max |round(0)|int }} "

- alias: bleach_inject
  id: '1559149426435'
  initial_state: true
  trigger: []
  condition: []
  action:
  - condition: state
    entity_id: input_boolean.lock_bleach
    state: 'off'
  - condition: numeric_state
    entity_id: input_number.bleach_inject
    value_template: "{{ states('input_number.bleach_inject')|float / states('input_number.capacity')|float }}"
    above: 10.0
    below: 200.0
  - entity_id: switch.orp
    service: switch.turn_on
  - data_template:
      message: "{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Bleach injection: ({{states('input_number.bleach_inject')}} ml)!!!"
    service: notify.pushbullet
  - delay: 00:00:{{ [0 , 60 * states('input_number.bleach_inject')|float/ states('input_number.bleach_speed')|float ]|max|int }}
  - entity_id: switch.orp
    service: switch.turn_off
  - data_template:
      message: "{{now().strftime('%H:%M')}}[{{now().day}}/{{now().month}}]"
      title: "Bleach injection end!!!"
    service: notify.pushbullet

