# Part of raspipool project @ github (by segalion at gmail)

switch:
  - platform: rpi_gpio
    ports:
# gpio_in_BCM_number: name
# example=> pin#35 = 'gpio.24' = rpi24 = BCM_19 => 19: pump
# execute 'gpio readall' to see all gpios an theis states in console
      19: Pump
      26: Turbo
      20: ph
      21: orp
    invert_logic: true

input_boolean:
  lock_bleach:
    initial: off
    icon: mdi:lock
  lock_muriatic:
    initial: off
    icon: mdi:lock


binary_sensor:
  - platform: template
    sensors:
      bleach:
        friendly_name: "Bleach injection"
        entity_id: 
          - switch.orp
          - input_boolean.lock_bleach
        device_class: plug
        value_template: "{{ is_state('switch.orp', 'on') }}"
        icon_template: >-
          {% if is_state('input_boolean.lock_bleach', 'on') %}
            mdi:lock
          {% endif %}
      muriatic:
        friendly_name: "Muriatic injection"
        entity_id: 
          - switch.ph
          - input_boolean.lock_muriatic
        device_class: plug
        value_template: "{{ is_state('switch.ph', 'on') }}"
        icon_template: >-
          {% if is_state('input_boolean.lock_muriatic', 'on') %}
            mdi:lock
          {% endif %}

