#https://www.home-assistant.io/components/sensor.command_line/
sensor:
  - platform: command_line
    name: RPI Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: last_boot
